config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users 
  resources :learn_tips 
  resources :lessons, only: [:index, :show] do 
    resources :learn_tips, only: [:index, :new]
  end 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  def dump_fixture
    fixture_file = "#{Rails.root}/test/fixtures/#{self.class.table_name}.yml"
    File.open(fixture_file, "a+") do |f|
      f.puts({ "#{self.class.table_name.singularize}_#{id}" => attributes }.
        to_yaml.sub!(/---\s?/, "\n"))
    end
  end
end

app/models/learn_tip.rb
class LearnTip < ApplicationRecord
belongs_to :user 
belongs_to :lesson 

validates :link, presence: true, length: {maximum: 255}
validates :name, presence: true, length: {maximum: 255}



end

app/models/lesson.rb
class Lesson < ApplicationRecord
    has_many :learn_tips
    has_many :users, through: :learn_tips

   validates_presence_of :name, :content, :order

end

app/models/user.rb
class User < ApplicationRecord
  has_many :learn_tips 
  has_many :lessons, through: :learn_tips

  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates_presence_of :name, :email
  validates :name, length: {maximum: 255}
  validates :email, length: {maximum: 255}, uniqueness: {case_sensitive: false}, format: { with: EMAIL_REGEX}
  validates :password, length: { minimum: 6 }, allow_nil: true
  validates :has_graduated, inclusion: { in: [true, false] }
  has_secure_password 


  def User.digest(string)  #needed to set up fixtures/users.yml Uses low 
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
end

app/controllers/learn_tips_controller.rb
class LearnTipsController < ApplicationController
  def new 
    if logged_in?
    @learn_tip = LearnTip.new 
    else  
      redirect_to login_path
    end 
  end 

  def create 
    if logged_in? 
      if @current_user.id == params[:learn_tip][:user_id].to_i
        @learn_tip = current_user.learn_tips.build(tip_params)
        if @learn_tip.save
          @learn_tip.save
          redirect_to lesson_learn_tips_url @learn_tip.lesson
        else 
         render 'new'
        end
      else
        redirect_to root_path 
      end  
    else 
      redirect_to login_path
    end  

  end 

  def show 
    @learn_tip = LearnTip.find(params[:id])
  end 

  def edit 
    if logged_in?
      @learn_tip = LearnTip.find(params[:id])

      if @learn_tip.user != current_user
         redirect_to root_path
      end 
    else  
      redirect_to login_path
    end 
  end 

  def update 
    @learn_tip = LearnTip.find(params[:id])

  if logged_in?
  
    if @learn_tip.user == current_user
      @learn_tip.update_attributes(tip_params)
      redirect_to @learn_tip
    else   
      redirect_to root_path 
    end 
  else 
   redirect_to root_path 
  end     
  end 

  def index 
    @index = LearnTip.all 
  end 

  def destroy 

    @learn_tip = LearnTip.find(params[:id])
    if current_user == @learn_tip.user 
      @learn_tip.destroy 
    end 
    redirect_to root_path
  end 

  private 

  def tip_params
    params.require(:learn_tip).permit(:name, :description, :link, :lesson_id, :user_id)
  end 
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  
    def show 
        @lesson = Lesson.find(params[:id])
    end 
  
  
    def index 
        @lessons = Lesson.all
    end 
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end 

  def create
      user = User.find_by(email: params[:session][:email].downcase)
      if user && user.authenticate(params[:session][:password])
          log_in(user)
          redirect_back_or user 
      else 
        render 'new'
      end 
    end 
  
    def destroy
      log_out if logged_in?
      redirect_to root_url
    end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
def home
end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new 
        @user = User.new 
    end 
  
    def create
        @user = User.new(user_params)
        if @user.save 
            redirect_to @user 
        else  
         render 'new'
        end 
    end 
  
    def show 
      set_user
    end 
  
    def edit
      if !logged_in?
        redirect_to login_path 
      else  
        set_user 
      end 
      redirect_to root_path unless @user == current_user
    end 
  
    def update 
        set_user
        if @user == current_user 
            redirect_to @user 
        else 
     redirect_to root_path
        end 

    
    end 
  
    def index 
      logged_in_user 
      @users = User.all  
    end 
  
    def destroy
        set_user 
        if current_user == @user 
            @user.destroy 
        end 
        redirect_to root_path
    end 

private
    def user_params
        params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation, :has_graduated)
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def logged_in_user
        unless logged_in?
          store_location 
          flash[:danger] = "Please log in."
          redirect_to login_url
        end
      end
    
      def store_location
        session[:forwarding_url] = request.original_url if request.get?
      end
      
    
      def set_user
        @user = User.find(params[:id])
      end 
    
      def correct_user 
        set_user
        redirect_to root_url unless @user == current_user
      end 
    
      def log_in(user)
        session[:user_id] = user.id
      end 
      
      def current_user
        if session[:user_id]
          @current_user ||= User.find_by(id: session[:user_id])  # Same as @current_user = @current_user || User.find_by(id: session[:user_id])
        end 
      end
    
      def logged_in?
         !current_user.nil?
      end 
      
      def log_out
        session.delete(:user_id)
        @current_user = nil
      end
    
      def log_in_as(user)
        session[:user_id] = user.id
      end
    
      #The below two methods are there to enable 'friendly-forwarding'.  If a user is prompted to log in when trying to access a page that requires login, then after providing credentials, the user experience is improved if the user is redirected to the original site they were trying to access.  
      def redirect_back_or(default)
        redirect_to(session[:forwarding_url] || default)
        session.delete(:forwarding_url)
      end
end

app/helpers/learn_tips_helper.rb
module LearnTipsHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    This page was created by a Flatiron student to help fellow learners and has not been endorsed by the Flatiron School.  
  </small>
  <nav>
    <ul>
   
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<!--Bootstrap header that displays different options depending on whether a user is logged in or not.  -->
<header class="navbar navbar-fixed-top">
  <div class="container" id="header">
    //<%= link_to "LearnHELP", root_path, id: "logo" %>
    <nav>
        <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Lessons", lessons_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Edit My Profile", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Sign Up", signup_path %></li>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
 <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsPortfolioProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag asset_path('favicon.ico') %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim'%>
  </head>

  <body>
   <%= render 'layouts/header' %>
  
    <div class="container">
      <% flash.each do |message_type, message| %> <!--flash = { success: "It worked!", danger: "It failed." }  message type is the key and message is the value-->
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
        <%= yield %>
         <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/learn_tips/_tip.html.erb
<li id="tip-<%= tip.id %>"> <!--  opens up the possibility of manipulating individual tips at a future date using JavaScrip -->
  <%= link_to gravatar_for(tip.user, size: 50), tip.user %>
  <span class="user"><%= link_to tip.user.name, tip.user %></span>
  <span class="title"><%= tip.title %></span><br>
  <span class="link"><%= tip.link %></span><br>
  <span class="description"><%= tip.description %></span><br>
  <span class="lesson"><%= tip.lesson.name %></span><br>
  <span class="timestamp">
    Posted <%= time_ago_in_words(tip.created_at) %> ago.
    <% if current_user?(tip.user) %>
      <%= link_to "delete", tip, method: :delete,
                                       data: { confirm: "Are you sure that you want to delete the tip #{tip.title}?" } %>
    <% end %>
  </span>
</li>

app/views/shared/_error_messages.html.erb
<!--'shared/error_messages'; this reflects the common Rails convention of using a dedicated shared/ directory for partials expected to be used in views across multiple controllers. -->

<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_tip_form.html.erb
<%= form_for(@tip, html: {class: 'form-group'}) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">

    <%= f.text_field :title, placeholder: "Add your title..." %>
    <%= f.text_field :link, placeholder: "Add your link..." %>
    <%= f.text_area :description, placeholder: "Add a description..." %>
    <%= f.select(:lesson_id, @options) %>

  </div>
  <%= f.submit "Post", class: "standard-input-button" %>
<% end %>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "My Profile", current_user %></span>
<span><%= pluralize(current_user.tips.count, "tip") %></span>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="tip_form">
        <%= render 'shared/tip_form' %>
      </section>
    </aside>
    <div class="col-md-8">
      <h3>Your Tips</h3>
      <%= render 'shared/feed' %>
    </div>
  </div>
<% else %>
  <div class="center jumbotron">
    <h1>Welcome to LearnHELP</h1>

    <h2>
      A place for students to provide targeted tips to others feeling the pain of learning something new. 
    </h2>
<button class = "standard-input-button">
    <%=link_to "Sign up now!", signup_path%>
</button><br><br>


<a href="/auth/facebook" class="btn btn-sm btn-social btn-facebook">
  <span class="fa fa-facebook"></span>
  Sign in with Facebook
</a>

<a href="/auth/github" class="btn btn-sm btn-social btn-github">
  <span class="fa fa-github"></span>
  Sign in with Github
</a>


  </div>
   <h3 id='plug'>What is the Flatiron School?  Who are you people? Check it out!     
  <%= link_to image_tag("learn.png", alt: "Learn Link"),
              'https://flatironschool.com/' %></h3>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "standard-input-button" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %> <!--defined in app/helpers/users_helper.rb -->
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "Are you sure you wish to delete #{user.name}?" } %>
  <% end %>
</li>

app/views/users/_user_with_tips.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
  <div class="col-md-8">
    <% if @user.tips.any? %>
      <h3>Tips (<%= @user.tips.count %>)</h3>
       <%= will_paginate @tips %>
      <ol class="tips">
        <%= render @tips %>
      </ol>
      <%= will_paginate @tips %>
    <% end %>
  </div>
</div>